context("Basic baggr() calls")

# prepare inputs ----------------------------------------------------------

# pooled
df1 <- data.frame("tau" = c(0,1), "se" = c(1,2))
# pooled, wide
df2 <- data.frame("tau" = c(.1,.1), "se.tau" = c(1,1),
                  "mu" = c(0,0), "se.mu" = c(1,1),
                  "site" = c("Site 1", "Site X"))
# individual
df3 <- data.frame(outcome = rnorm(100),
                  site = rep(c("A", "B", "C", "D"), each = 25),
                  treatment = rbinom(100, 1, .5))
# individual, custom column names
df4 <- data.frame(profit = rnorm(100),
                  village = rep(c("A", "B", "C", "D"), each = 25),
                  ITT = rbinom(100, 1, .5))



# tests ----------------------------------------------------------
test_that("Error messages for wrong inputs are in place", {
  # model doesn't exist
  expect_error(baggr(df1, "made_up_model"), "Unrecognised model")
  # wrong model for this data
  expect_error(baggr(df1, "mutau"), "Data provided is of type")
  # Stan warnings will be generated by default:
  expect_warning(baggr(df1, "rubin"), "divergent transitions")
})

# correct model
# expect_is(baggr(df1, "rubin"), "stanfit")


test_that("Extra args passed via ... work well", {
  bgf <- baggr(df1, "rubin", iter = 200, chains = 2)$fit
  expect_equal(nrow(as.matrix(bgf)), 200)
})

df5 <- data.frame("tau" = c(1, -1, .5, -.5, .7, -.7, 1.3, -1.3),
                  "se" = rep(1, 8),
                  "state" = datasets::state.name[1:8])

bg5_n <- baggr(df5, "rubin", pooling = "none", grouping = "state",
               iter = 200, chains = 2)
bg5_p <- baggr(df5, "rubin", pooling = "partial", grouping = "state",
               iter = 200, chains = 2)
bg5_f <- baggr(df5, "rubin", pooling = "full", grouping = "state",
               iter = 200, chains = 2)

# test_that("Basic Rubin model has sensible results", {
# ...
# })

bg2 <- baggr(df2, "mutau")
bg3 <- baggr(df4, "joint",
             grouping = "village", outcome = "profit", treatment = "ITT")

test_that("Plotting works", {
  # plots happen at all with vanilla settings
  expect_is(plot(bg5_n), "gg")
  expect_is(plot(bg2), "gg")
  expect_is(plot(bg3), "gg")
  # we can crash it
  expect_error(plot(bg5_n, style = "rubbish"), "argument must be one of")
})


#
# bg1 <- baggr(df1, "rubin")

# class(bg)
#
# # naming of sites
bg_sites <- baggr(data.frame(df1, "site" = LETTERS[1:nrow(df1)]), "rubin")
# plot(bg_sites)

# #different kinds of pooling:
# bg_none <- baggr(df1, "rubin", pooling = "none")
# bg_partial <- baggr(df1, "rubin", pooling = "partial")
# # bg_full <- baggr(df1, "rubin", pooling = "full")
